### ISSUE TITLE
Detect non-government emails (PII) in metadata or data

### ISSUE THREAD

**Issue by juddpatterson** [nationalparkservice/DPchecker#101]
**Describe the solution you'd like**
I wonder if it's worth a rudimentary sensitive PII scanner, specifically to warn folks if they include non-government email addresses. Detecting .edu, .com, etc. emails may be challenging, but a pretty simpler implementation could look for gmail.com, yahoo.com, hotmail.com, and perhaps a few other common email domains?
https://www.thewindowsclub.com/commonly-used-email-addresses

**Additional context**
This is definitely not a high priority, but could catch data that I suspect is occasionally (accidentally) shared.

**Comment by RobLBaker** [comment]
I don't think it should be too hard to look for emails and filter out .govs.  This is a great idea!
