### ISSUE TITLE
Check that dates are within stated metadata bounds

### ISSUE THREAD

**Issue by wright13** [nationalparkservice/DPchecker#16]
Compare date range in attribute metadata to that at dataset level. Must honor content of the required attribute "exclusive". Throw warning on failure.

**Comment by wright13** [comment]
Questions:
- What do we want this to return if there are no bounds on date/time attributes?
- Should we test the actual contents of the dataset or just the metadata?

**Comment by RobLBaker** [comment]
I think the idea is to get the beginDate and endDate from metadata and then make sure all the data points within the various data files fall within that range.

**Comment by wright13** [comment]
Ok that's what I originally thought, but it looks like the "exclusive" attribute only shows up in the attribute-level bounds. Unless I'm just failing at EML which is very possible.

**Comment by wright13** [comment]
1. I think it's reasonable to restrict the scope of this fxn to columns identified in the metadata as date/time. 
2. If we restrict ourselves to columns labeled as date/time in the eml, we should be able to use the date/time format string to help with this
3. I can't think of any but I'm sure theyr'e out there. If we throw a warning instead of an error, it's probably acceptable to let the user decide whether it's ignorable. Alternately we could include an optional argument for users to specify any date/time columns that the test should skip.

**Comment by RobLBaker** [comment]
Warning seems appropriate. Especially if you look at BUIS example, which has 3 different date columns in a single table.
