### ISSUE TITLE
argument "element" is missing, with no default

### ISSUE THREAD

**Issue by juddpatterson** [nationalparkservice/DPchecker#44]
New EML file and a new little hiccup. Most of the way through the checks a parsing issue appears and a missing element is mentioned. It then completes the summary, but shows a warning and error that were not printed previously.

![image](https://user-images.githubusercontent.com/50838982/218214103-9f402f59-3391-42c9-859c-f78e09e498f6.png)

**Comment by juddpatterson** [comment]
FYI, Sarah shared that it may be a special character and/or UTF-8 issue causing the parsing issue.

**Comment by RobLBaker** [comment]
https://github.com/nationalparkservice/DPchecker/pull/69
