### ISSUE TITLE
check metadata for title

### ISSUE THREAD

**Issue by RobLBaker** [nationalparkservice/DPchecker#50]
title (eml/dataset/title)

Work in some best practices tests:
-Is it 10 words or less?

**Comment by RobLBaker** [comment]
@juddpatterson should this incorporate any of the additional requirements we have for data package cleanup SOPs? Should it look for a year? Park Unit? State, etc?

**Comment by juddpatterson** [comment]
Thinking this through, 10 does seem pretty restrictive and 15 sounds better. I'm sending you an export of current tiles from DataStore which might be interesting to mine a little bit as well.

**Comment by RobLBaker** [comment]
see test_dp_title()
